felladrin/MiniSearch

src/index.tsx

Add a Settings Menu with options to toggle links summarization and usage of a larger model

---

.github/workflows/check-docker-container.yml

Add a GitHub action to check if the docker image is working

---

.dockerignore
Dockerfile
README.md
docker-compose.production.yml
docker-compose.yml
server.ts
vite.config.ts

Use SearXNG as the metasearch engine

---

package-lock.json
package.json
src/components/ConfigForm.tsx
src/components/ResponseView.tsx
src/components/SearchResultsList.tsx
src/index.tsx

- Resolves https://github.com/felladrin/MiniSearch/issues/19

Replace `title` properties on html elements with a proper tooltip

---

src/modules/textGeneration.ts
src/modules/transformers.ts

This should improve the performance of the responses when using transformer.js, since the context is bigger and the model has been trained with questions-and-answers-from-context.

Use a text-generation model in place of the text-to-text-generation one

---

hf-space-config.yml
server.ts

If you want to run it with COEP/COOP header inside HF iframe, all sub resources are also required to provide the headers.
ps. I notice you're syncing your repo with HF so I'm sending you the PR here

Add COOP/COEP headers

---

src/components/SearchResultsList.tsx

Another small fix, inside HF iframe, you want to load links on an external tab

target blank  on links

---

package-lock.json
package.json
server/fetchSearXNG.ts

This commit replaces the existing search functionality with the Searxng library.
It solves the limitations and issues present in the previous search implementation by leveraging the advanced capabilities of the Searxng library.
- Ensure the Searxng service is running at `http://127.0.0.1:8080/search`.
- Start your application that integrates the new search functionality.
- Perform various search queries through the application interface to test the new functionality.
- Check that the search results are accurately returned from the Searxng service.
- Ensure the results are correctly formatted and displayed in the application.

feat(server): replace existing search functionality with searxng library

---

.github/workflows/update-searxng-docker-image.yml

This ensures the project consistently uses the latest stable releases of SearXNG without manual intervention.

Add a GitHub Actions workflow to automate the process of updating the SearXNG Docker image within the repository

---

client/components/Pages/Main/Menu/InterfaceSettingsForm.tsx
client/components/Pages/Main/Menu/MenuDrawer.tsx
client/components/Pages/Main/Menu/SearchSettingsForm.tsx

The 'Image Search' was previously under 'Interface Settings'.

Add the section 'Search Settings' in the Menu and move the 'Image Search' setting into it

---

client/components/Pages/Main/Menu/SearchSettingsForm.tsx
client/modules/settings.ts
client/modules/textGeneration.ts

Add "Search Results Limit" setting, configurable with slider control

---

server/fetchSearXNG.ts

These changes optimize the `fetchSearXNG` function by improving performance and maintainability without altering existing functionality. 
Run searches and confirm if the results are returned as usual.

Refactor fetchSearXNG to process results concurrently

---

client/components/Pages/Main/Menu/AISettingsForm.tsx
client/modules/textGenerationUtilities.ts
client/modules/textGenerationWithWllama.ts
client/modules/wllama.ts

Allow users to customize AI inference parameters such as Temperature, Top P, Frequency Penalty, and Presence Penalty

---

client/components/AiResponse/FormattedMarkdown.tsx

- Added `CopyIconButton` for copying code snippets.
- Integrated `remark-gfm` for GitHub Flavored Markdown support.
- Enhanced code block rendering with custom styles and improved table handling.
- Updated component structure for better readability and maintainability.

Refactor `FormattedMarkdown` component to improve code rendering with copy functionality and table styling

---

client/components/Search/Results/SearchResultsSection.tsx

- Added ErrorBoundary and loading fallback components to manage errors and loading states for search results.
- Implemented conditional rendering based on enabled search types, displaying alerts when no search types are enabled.
- Refactored search results rendering into a reusable function for cleaner code.

Improve SearchResultsSection with error and loading handling

---

.github/workflows/llama-cpp.yml

This should give better analysis of Pull Requests, even with so high quantization.

Use a larger model for AI Review

---

.github/workflows/llama-cpp.yml
client/modules/textGenerationWithWllama.ts
client/modules/wllama.ts
package-lock.json
package.json

So @huggingface/jinja dependency can be removed.

Use the modern `createChatCompletion` method from Wllama

---

client/modules/settings.ts

Now it contains instructions for citing for any information that is not common knowledge.

Improve the default Instructions for AI

---

.github/workflows/llama-cpp.yml

Update the GitHub Actions workflow to use a different model and introduces several changes to the workflow steps.

Improve AI PR Review

---

client/modules/wllama.ts

This might alleviate the issue on iOS devices, which, when running larger models, can only succeed in running in multi-thread mode after it has been run in single-thread mode first.

Warmup the Wllama model with a single CPU thread before actually initializing it in multi-thread mode

---

client/components/Pages/Main/Menu/AISettings/components/AIParameterSlider.tsx
client/components/Pages/Main/Menu/AISettings/components/BrowserSettings.tsx
client/components/Pages/Main/Menu/AISettings/components/HordeSettings.tsx
client/components/Pages/Main/Menu/AISettings/components/OpenAISettings.tsx
client/components/Pages/Main/Menu/AISettings/components/SystemPromptInput.tsx
client/components/Pages/Main/Menu/AISettings/hooks/useHordeModels.ts
client/components/Pages/Main/Menu/AISettings/hooks/useHordeUserInfo.ts
client/components/Pages/Main/Menu/AISettings/hooks/useOpenAiModels.ts
client/components/Pages/Main/Menu/AISettings/index.tsx
client/components/Pages/Main/Menu/AISettings/types.ts

This makes easier to maintain it.

Refactor the AI Settings menu section so it's composed of small files

---

server/searchEndpointServerHook.ts

Set a timeout of one second for fetching an image thumbnail

---

client/components/AiResponse/FormattedMarkdown.tsx
client/components/AiResponse/ReasoningSection.tsx
client/components/AiResponse/hooks/useReasoningContent.ts
client/components/Pages/Main/Menu/AISettings/AISettingsForm.tsx
client/modules/settings.ts
client/modules/stringFormatters.ts

Add AI reasoning section with custom markers

---

client/components/Pages/Main/Menu/ClearDataButton.tsx
client/modules/search.ts
package-lock.json
package.json

To make it easier to maintain.

Refactor search caching to use Dexie.js

---

.github/workflows/update-searxng-docker-image.yml
Dockerfile
README.md

- Reference: https://github.com/searxng/searxng/pull/4721

Migrate base image from Alpine to Debian for compatibility with the latest SearXNG docker image

---

client/components/AiResponse/EnableAiResponsePrompt.tsx
client/components/Pages/Main/MainPage.tsx
client/modules/settings.ts

Add AI response opt-in prompt for first-time users
